name: Minecraft Status

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install mcstatus
        run: pip install mcstatus

      - name: Check server and send webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MC_HOST: ${{ secrets.MC_HOST }}
          MC_PORT: ${{ secrets.MC_PORT }}
        run: |
          python3 - <<'PY'
          import json
          import os
          import urllib.request
          from mcstatus import JavaServer

          webhook = os.environ["DISCORD_WEBHOOK"]
          host = os.environ["MC_HOST"]
          port = int(os.environ["MC_PORT"])

          try:
              server = JavaServer.lookup(f"{host}:{port}")
              status_data = server.status()

              player_online = status_data.players.online
              player_max = status_data.players.max
              status = "🟢 Online"
              players = f"{player_online}/{player_max}"
              color = 3066993

          except Exception:
              status = "🔴 Offline"
              players = "0/0"
              color = 15158332

          payload = {
              "embeds": [
                  {
                      "title": "Minecraft Server",
                      "color": color,
                      "fields": [
                          {"name": "STATUS", "value": f"`{status}`", "inline": True},
                          {"name": "PLAYERS", "value": f"`{players}`", "inline": True},
                          {"name": "SERVER INFO", "value": "`1.21.11 Server ip:SMPVIRTUVE.aternos.me:57445`", "inline": False}
                      ]
                  }
              ]
          }

          req = urllib.request.Request(
              webhook,
              data=json.dumps(payload).encode("utf-8"),
              headers={"Content-Type": "application/json"},
              method="POST"
          )

          urllib.request.urlopen(req, timeout=20)
          print("Sent webhook")
          PY
